### ISSUE TITLE
Dependency Update

### ISSUE THREAD

**Issue by Spectre5** [compmec/section#21]
In the pyproject.toml file this depends on both of the following:
```toml
compmec-nurbs = "^1.0.0"
compmec-shape = "^1.0.0"
```

But I think these have been renamed to `pynurbs` and `shapepy`, which both have more recent releases on PyPI than the compmec ones.
